import streamlit as st
import re
from datetime import datetime
import textwrap

def parse_meeting_notes(raw_text):
    """Parse raw meeting notes into structured sections."""
    lines = raw_text.strip().split('\n')
    
    sections = {
        'header': '',
        'attendees': [],
        'agenda': [],
        'discussion': [],
        'decisions': [],
        'action_items': [],
        'follow_ups': [],
        'notes': []
    }
    
    current_section = 'notes'
    action_pattern = re.compile(r'^(action|todo|to.?do|owner):?\s*(.*)', re.IGNORECASE)
    decision_pattern = re.compile(r'^(decision|decided|agree|consensus):?\s*(.*)', re.IGNORECASE)
    followup_pattern = re.compile(r'^(follow.?up|next.?steps|pending):?\s*(.*)', re.IGNORECASE)
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        # Detect section headers
        lower_line = line.lower()
        if 'attendee' in lower_line or 'present' in lower_line:
            current_section = 'attendees'
            continue
        elif 'agenda' in lower_line:
            current_section = 'agenda'
            continue
        elif 'discussion' in lower_line:
            current_section = 'discussion'
            continue
        elif 'decision' in lower_line:
            current_section = 'decisions'
            continue
        elif 'action' in lower_line and 'item' in lower_line:
            current_section = 'action_items'
            continue
        elif 'follow' in lower_line and 'up' in lower_line:
            current_section = 'follow_ups'
            continue
            
        # Check for inline markers
        action_match = action_pattern.match(line)
        decision_match = decision_pattern.match(line)
        followup_match = followup_pattern.match(line)
        
        if action_match:
            sections['action_items'].append(action_match.group(2).strip() or action_match.group(0))
        elif decision_match:
            sections['decisions'].append(decision_match.group(2).strip() or decision_match.group(0))
        elif followup_match:
            sections['follow_ups'].append(followup_match.group(2).strip() or followup_match.group(0))
        else:
            sections[current_section].append(line)
    
    return sections

def format_summary(sections, client_name, project_name):
    """Format parsed sections into a professional summary."""
    now = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    
    summary = []
    summary.append("=" * 60)
    summary.append(f"MEETING SUMMARY")
    summary.append("=" * 60)
    summary.append(f"Client: {client_name}")
    summary.append(f"Project: {project_name}")
    summary.append(f"Date: {now}")
    summary.append("")
    
    # Attendees
    if sections['attendees']:
        summary.append("ATTENDEES")
        summary.append("-" * 40)
        for person in sections['attendees']:
            summary.append(f"• {person}")
        summary.append("")
    
    # Agenda
    if sections['agenda']:
        summary.append("AGENDA")
        summary.append("-" * 40)
        for item in sections['agenda']:
            summary.append(f"• {item}")
        summary.append("")
    
    # Discussion
    if sections['discussion']:
        summary.append("DISCUSSION POINTS")
        summary.append("-" * 40)
        for point in sections['discussion']:
            summary.append(f"• {point}")
        summary.append("")
    
    # Decisions
    if sections['decisions']:
        summary.append("KEY DECISIONS")
        summary.append("-" * 40)
        for decision in sections['decisions']:
            summary.append(f"✓ {decision}")
        summary.append("")
    
    # Action Items
    if sections['action_items']:
        summary.append("ACTION ITEMS")
        summary.append("-" * 40)
        for i, item in enumerate(sections['action_items'], 1):
            summary.append(f"{i}. {item}")
        summary.append("")
    
    # Follow-ups
    if sections['follow_ups']:
        summary.append("FOLLOW-UPS")
        summary.append("-" * 40)
        for item in sections['follow_ups']:
            summary.append(f"→ {item}")
        summary.append("")
    
    # Additional notes
    if sections['notes']:
        summary.append("ADDITIONAL NOTES")
        summary.append("-" * 40)
        for note in sections['notes']:
            summary.append(f"• {note}")
        summary.append("")
    
    summary.append("=" * 60)
    summary.append("Generated by Meeting Notes Formatter")
    
    return '\n'.join(summary)

def main():
    st.set_page_config(
        page_title="Meeting Notes Formatter",
        page_icon="📝",
        layout="centered"
    )
    
    st.title("📝 Meeting Notes Formatter")
    st.markdown("Transform raw meeting notes into professional client-ready summaries")
    
    # Sidebar for client info
    with st.sidebar:
        st.header("Client Information")
        client_name = st.text_input("Client Name", value="Client")
        project_name = st.text_input("Project Name", value="Project")
        
        st.markdown("---")
        st.markdown("**How to use:**")
        st.markdown("1. Paste your raw meeting notes")
        st.markdown("2. Click 'Format Notes'")
        st.markdown("3. Download the formatted summary")
    
    # Main content area
    col1, col2 = st.columns([3, 1])
    
    with col1:
        raw_notes = st.text_area(
            "Paste your meeting notes here:",
            height=300,
            placeholder="Paste raw meeting notes...\n\nTip: Use labels like 'Decision:', 'Action:', 'Follow-up:' for better parsing"
        )
    
    with col2:
        st.markdown("### Quick Tips")
        st.markdown("""
        - **Decisions:** Start with 'Decision:'
        - **Actions:** Start with 'Action:' or 'Todo:'
        - **Follow-ups:** Start with 'Follow-up:'
        - Use section headers like 'Attendees:', 'Agenda:'
        """)
    
    # File upload option
    uploaded_file = st.file_uploader("Or upload a text file", type=['txt'])
    if uploaded_file is not None:
        raw_notes = uploaded_file.read().decode('utf-8')
        st.success("File uploaded successfully!")
    
    if st.button("📋 Format Notes", type="primary", use_container_width=True):
        if not raw_notes.strip():
            st.error("Please provide meeting notes to format.")
            return
        
        try:
            with st.spinner("Formatting your notes..."):
                sections = parse_meeting_notes(raw_notes)
                formatted_summary = format_summary(sections, client_name, project_name)
            
            st.success("Notes formatted successfully!")
            
            # Display formatted output
            st.subheader("Formatted Summary")
            st.text_area("Preview", formatted_summary, height=400)
            
            # Download button
            st.download_button(
                label="📥 Download Summary",
                data=formatted_summary,
                file_name=f"meeting_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
                mime="text/plain",
                use_container_width=True
            )
            
        except Exception as e:
            st.error(f"An error occurred while formatting: {str(e)}")
            st.info("Please check your notes and try again.")
    
    # Footer
    st.markdown("---")
    st.markdown("Made for consultants who value their time ⏰")

if __name__ == "__main__":
    main()